/* THIS FILE WILL BE OVERWRITTEN BY DEV-C++ */
/* DO NOT EDIT ! */

#ifndef BANJIUGAMELAUNCHER_PRIVATE_H
#define BANJIUGAMELAUNCHER_PRIVATE_H

/* VERSION DEFINITIONS */
#define VER_STRING	"0.0.0.3"
#define VER_MAJOR	0
#define VER_MINOR	0
#define VER_RELEASE	0
#define VER_BUILD	3
#define COMPANY_NAME	"Saohuo Lianmeng Studio"
#define FILE_VERSION	"0.0.0.3"
#define FILE_DESCRIPTION	""
#define INTERNAL_NAME	""
#define LEGAL_COPYRIGHT	""
#define LEGAL_TRADEMARKS	""
#define ORIGINAL_FILENAME	""
#define PRODUCT_NAME	""
#define PRODUCT_VERSION	"0.0.0.3"

#endif /*BANJIUGAMELAUNCHER_PRIVATE_H*/
